scrape_configs:

- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets:
      - cadvisor:8080

- job_name: flower
  scrape_interval: 5s
  static_configs:
    - targets:
      # Because we use nginx as reverse proxy for flower
      - nginx:5555
  basic_auth:
    username: admin
    password: admin
