#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A django_celery_example inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

exec celery flower \
    --app=django_celery_example \
    --broker="${CELERY_BROKER}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"

# If you want to make flower keeps the task info after restart, pass options like this --persistent=1 --db=flower.db
# You should also create docker volume to keep db file
